//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopolio_RS232.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monopolio_RS232.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediterranean Ave.,2,60,2,Purple
        ///Baltic Ave.,4,60,4,Purple
        ///Oriental Ave.,7,100,6,Light-Blue
        ///Vermont Ave.,9,100,6,Light-Blue
        ///Connecticut Ave.,10,120,8,Light-Blue
        ///St. Charles Place,12,140,10,Violet
        ///States Ave.,14,140,10,Violet
        ///Virginia Ave.,15,160,12,Violet
        ///St. James Place,17,180,14,Orange
        ///Tennessee Ave.,19,180,14,Orange
        ///New York Ave.,20,200,16,Orange
        ///Kentucky Ave.,22,220,18,Red
        ///Indiana Ave.,24,220,18,Red
        ///Illinois Ave.,25,240,20,Red
        ///Atlantic Ave.,27,260,22,Yellow
        ///Ventnor Ave.,28,260,22,Yellow
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Propiedades {
            get {
                return ResourceManager.GetString("Propiedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tablero {
            get {
                object obj = ResourceManager.GetObject("tablero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
